name: CI/CD using Github Actions & AWS CodeDeploy # Workflow 이름

on: 
  release:
    types: [push] 
  push:
    branches: [master] 

jobs: 
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

 
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

       # 프로젝트 압축
    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
        
      # AWS 사용자 정보 입력
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ap-northeast-2
          
      # S3에 zip 파일 업로드
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy/$GITHUB_SHA.zip --source .

       # CodeDeploy에 배포 요청
    - name: Code Deploy
      run: aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{ secrets.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=deploy/$GITHUB_SHA.zip
